### ISSUE TITLE
Incorrectly decompresses non UTF-8 data

### ISSUE THREAD

**Issue by Gromolyak** [siara-cc/Unishox#3]
static const char cszData[] = "\x41\x5F\x28\xE1\xF3\xEA\xE2\xE0\x29";

		char chBuf[ 0x100 ];
		char chBuf1[ 0x100 ];

		int nRes;
		nRes = unishox1_compress( cszData, sizeof( cszData ) - 1, chBuf, 0 );
		nRes = unishox1_decompress( chBuf, nRes, chBuf1, 0 ); // incorrect result!

**Comment by siara-cc** [comment]
Is the input valid UTF-8 string?  I don't remember whether binary data is supported or not.
But you should be able to encode and decode UTF-8 sequences correctly.

**Comment by Gromolyak** [comment]
No, it is not a valid UTF-8 string.
It is not very clear from the description that ONLY valid UTF-8 code words are allowed on input.
Thank you for your job anyway.
