### ISSUE TITLE
Can we compress .txt file in zip format and decompress it on windows/server?

### ISSUE THREAD

**Issue by bhupiister** [siara-cc/Unishox#4]
I have a data-log file in .txt format of 2Mb each. Need to compress it in zip format (filename.zip) and send it over the GPRS to web server, there the web server can again decompress it. Is it possible by this library?

**Comment by siara-cc** [comment]
Sorry this is a new format and cannot compress as any standard formats such as zip, gz, tgz, bz or 7z.

**Comment by bhupiister** [comment]
@siara-cc Can we use the same format of yours and decompress the data on the web?
