### ISSUE TITLE
There's no parameter for output buffer length

### ISSUE THREAD

**Issue by habnabit** [siara-cc/Unishox#5]
`unishox1_{de,}compress` will gladly write beyond the end of the output buffer because there's no way to know that they're at the end. This is exacerbated given that there's no way to know in advance what the output size will be from the input, so there's no way to choose a buffer size without the danger of an overrun. 

Both of these are issues worth solving, though technically either one will kind of obviate the other. If I were to choose just one, I'd pick "output buffer length as a parameter" over "output length calculator".

**Comment by siara-cc** [comment]
Please see my reply here:
https://github.com/siara-cc/Unishox/issues/7#issuecomment-723476532
Will it help in passing the correct len to unishox1_decompress()?

**Comment by habnabit** [comment]
Yes, it is possible to transmit this data out of band, but I think that's a disappointing answer when this is a solvable problem.

**Comment by siara-cc** [comment]
I thought it was a problem of not being able to provide a buffer that has enough length as the calling program would have no idea of how much the compressed bytes would expand to.
If you think there is a problem in the library that getBitVal reads beyond even if the correct length is given, I will check and correct it. Thanks.

**Comment by gzm55** [comment]
in test codes, the case [here](https://github.com/siara-cc/Unishox/blob/master/test_unishox2.c#L515) will overwrite a character out of the buffer `dbuf`. so i think output buffer length is needed to detect the error.
